# Generated by Django 5.0.4 on 2024-04-24 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catNombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodCodigo', models.IntegerField(unique=True)),
                ('prodNombre', models.CharField(max_length=50)),
                ('prodPrecio', models.IntegerField()),
                ('prodFoto', models.FileField(blank=True, null=True, upload_to='fotos/')),
                ('prodCategoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appTienda.categoria')),
            ],
        ),
    ]
